version: "3.8"

networks:
  fti-network:
    driver: bridge

services:
  intake:
    build: .
    image: fti-intake
    container_name: fti-backend
    networks:
      - fti-network

    # Run from project root inside container
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=YOUR_GEMINI_API_KEY

    # Volumes (MOST IMPORTANT PART)
    volumes:
      # Source code (for reference + live editing)
      - ./:/app

      # Malware samples (READ-ONLY for safety)
      - ./data/samples:/app/data/samples

      # Generated features & reports (WRITEABLE, persisted)
      - ./data/features:/app/data/features


    # Disable network for malware safety (OPTIONAL but recommended)
    # network_mode: "none"

  frontend:
    build: ./frontend
    container_name: fti-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - fti-network
    depends_on:
      - intake
