version: "3.8"

networks:
  fti-network:
    driver: bridge

services:
  intake:
    build: .
    image: fti-intake
    container_name: fti-backend
    networks:
      - fti-network

    # Run from project root inside container
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=AIzaSyAAJiTVHkO7zssHvtG86OJH1rVbc1DmoKM
      - MODELS_DIR=/app/data/global_models
      - AGGREGATOR_URL=http://aggregator:8001
      - CLIENT_ID=fti-node-1

    # Volumes (MOST IMPORTANT PART)
    volumes:
      # Source code (for reference + live editing)
      - ./:/app

      # Malware samples (READ-ONLY for safety)
      - ./data/samples:/app/data/samples

      # Generated features & reports (WRITEABLE, persisted)
      - ./data/features:/app/data/features

      # Global models
      - ./data/global_models:/app/data/global_models

    # Disable network for malware safety (OPTIONAL but recommended)
    # network_mode: "none"

  aggregator:
    build: 
      context: .
      dockerfile: Dockerfile.aggregator
    container_name: fti-aggregator
    networks:
      - fti-network
    ports:
      - "8001:8001"
    environment:
      - MODELS_DIR=/app/models
    volumes:
      - ./data/global_models:/app/models

  frontend:
    build: ./frontend
    container_name: fti-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - fti-network
    depends_on:
      - intake

